// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'blockContent': string;
  'blockID': string;
  'blockLabel': string;
  'blockName': string;
  'blockOptions': string;
  'content': string;
  'contentWell': string;
  'delete': string;
  'dot': string;
  'editView': string;
  'empty': string;
  'enterNode': string;
  'exitNode': string;
  'grabber': string;
  'highlightBorder': string;
  'invisible': string;
  'label': string;
  'node': string;
  'nodeAction': string;
  'nodeBar': string;
  'nodeContent': string;
  'nodeLabel': string;
  'optionButton': string;
  'optionMenu': string;
  'sideNode': string;
  'transitionContent': string;
  'wellLabel': string;
}
declare var cssExports: CssExports;
export = cssExports;
