// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add': string;
  'block': string;
  'blockLabel': string;
  'blockOptions': string;
  'blockWell': string;
  'container': string;
  'content': string;
  'delete': string;
  'dynamicInputButton': string;
  'grabber': string;
  'inspectorWindow': string;
  'label': string;
  'messageContainer': string;
  'messageHeader': string;
  'messages': string;
  'msg': string;
  'msgComponent': string;
  'nodeName': string;
  'option': string;
  'optionButton': string;
  'optionLabel': string;
  'optionMenu': string;
  'options': string;
  'optionsHeader': string;
  'placeholderText': string;
  'req': string;
  'tabsBar': string;
  'text': string;
}
declare var cssExports: CssExports;
export = cssExports;
