// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add': string;
  'block': string;
  'blockOptions': string;
  'blockWell': string;
  'container': string;
  'content': string;
  'delete': string;
  'grabber': string;
  'nodeInspector': string;
  'nodeName': string;
  'option': string;
  'optionButton': string;
  'optionLabel': string;
  'optionMenu': string;
  'options': string;
  'optionsHeader': string;
  'tabsBar': string;
}
declare var cssExports: CssExports;
export = cssExports;
