// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add': string;
  'block': string;
  'blockOptions': string;
  'blockWell': string;
  'content': string;
  'delete': string;
  'option': string;
  'optionButton': string;
  'optionLabel': string;
  'optionMenu': string;
}
declare var cssExports: CssExports;
export = cssExports;
